# Description:
#   This creates a Kali runtime environment for the qBittorrent Application
# Usage:
#   From this directory, run $ sudo docker build -t tkalirunenv:latest .

# By default, runs as root
# List of containers for kali are here:
# https://gitlab.com/kalilinux/build-scripts/kali-docker/container_registry

# Pull kali:2019.4
FROM registry.gitlab.com/kalilinux/build-scripts/kali-docker/kali:2019.4

#update and upgrade
RUN apt-get update
RUN apt-get upgrade -y

#install utilities and dependencies
RUN apt-get install apt-utils dpkg-dev net-tools iputils-ping systemd texinfo -y
RUN apt-get install libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev libgeoip-dev -y
RUN apt-get install qtbase5-dev qttools5-dev-tools libqt5svg5-dev -y
RUN apt-get install zlib1g-dev -y

# Finished!
RUN echo 'Container is ready, run it using $ sudo docker run --name kalirunenv -it -d tkalirunenv:latest bash'
