# Description:
#   This runtime environment example Dockerfile creates a container with a minimal Ubuntu server and nginx server
# Usage:
#   From this directory, run $ sudo docker build -t tsuricata .
# By default, runs as root
FROM ubuntu:18.04

ENV DEBIAN_FRONTEND noninteractive
# Setup ENV for systemd
ENV container docker

#update and upgrade
RUN apt-get update
RUN apt-get upgrade -y

#install utilities and dependencies
RUN apt-get install apt-utils dpkg-dev net-tools iputils-ping -y
RUN apt-get install vim wget software-properties-common -y
RUN apt-get install systemd systemd-sysv -y

# install Suri
RUN add-apt-repository ppa:oisf/suricata-stable
RUN apt-get update -y
RUN apt-get install suricata -y
RUN apt-get install suricata-dbg -y


VOLUME [ "/sys/fs/cgroup" ]

# Finished!
RUN echo 'Container is ready, run it using $ sudo docker run -d --name suricata --privileged -v /sys/fs/cgroup:/sys/fs/cgroup:ro --network host tsuricata:latest'
RUN echo 'Then attach to it using $ sudo docker exec -it suricata bash'

CMD ["/lib/systemd/systemd"]