# Description:
#   This creates a Ubuntu running Docker environment for the qBittorrent Application
# Usages:
#   From this directory, run $ sudo docker build -t tubunturunenv .

# By default, runs as root
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND noninteractive
# Setup ENV for systemd
ENV container docker

#update and upgrade
RUN apt-get update
RUN apt-get upgrade -y

#install utilities and dependencies
RUN apt-get install apt-utils dpkg-dev net-tools iputils-ping pkg-config systemd textinfo -y
RUN apt-get install libboost-dev libboost-system-dev libboost-chrono-dev libboost-random-dev libssl-dev libgeoip-dev -y
RUN apt-get install qtbase5-dev qttools5-dev-tools libqt5svg5-dev -y
RUN apt-get install zlib1g-dev -y

# Finished!
RUN echo 'Container is ready, run it using $ sudo docker run --name ubunturunenv -it -d tubunturunenv:latest bash'

CMD ["/lib/systemd/systemd"]

#https://hub.docker.com/r/jrei/systemd-ubuntu/dockerfile
